//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23DC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("grond,Verdieping")]
        public string FloorKW {
            get {
                return ((string)(this["FloorKW"]));
            }
            set {
                this["FloorKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("doorsnede")]
        public string SectionKW {
            get {
                return ((string)(this["SectionKW"]));
            }
            set {
                this["SectionKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gevel")]
        public string ElevationKW {
            get {
                return ((string)(this["ElevationKW"]));
            }
            set {
                this["ElevationKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\")]
        public string catchEcapPath {
            get {
                return ((string)(this["catchEcapPath"]));
            }
            set {
                this["catchEcapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MAATVOERING")]
        public string LevelLayername {
            get {
                return ((string)(this["LevelLayername"]));
            }
            set {
                this["LevelLayername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUITENWAND")]
        public string WallKW {
            get {
                return ((string)(this["WallKW"]));
            }
            set {
                this["WallKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\")]
        public string catchIcapPath {
            get {
                return ((string)(this["catchIcapPath"]));
            }
            set {
                this["catchIcapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Export>\r\n    <CAP>\r\n       <Levels>\r\n   " +
            "         <Level0>\r\n                <Level_Name>Ground Floor</Level_Name>\r\n      " +
            "          <Level_Number>0</Level_Number>\r\n                <Level_Value>0</Level_" +
            "Value>\r\n            </Level0>\r\n            <Level1>\r\n                <Level_Name" +
            ">1st Floor</Level_Name>\r\n                <Level_Number>1</Level_Number>\r\n       " +
            "         <Level_Value>2880</Level_Value>\r\n            </Level1>\r\n            <Le" +
            "vel2>\r\n                <Level_Name>2nd Floor</Level_Name>\r\n                <Leve" +
            "l_Number>2</Level_Number>\r\n                <Level_Value>5760</Level_Value>\r\n    " +
            "        </Level2>\r\n            <Level3>\r\n                <Level_Name>3rd Floor</" +
            "Level_Name>\r\n                <Level_Number>3</Level_Number>\r\n                <Le" +
            "vel_Value>10550</Level_Value>\r\n            </Level3>\r\n        </Levels>\r\n       " +
            " <Floors>\r\n            <Hatch1>\r\n                <Level_Name>1stfloor</Level_Nam" +
            "e>\r\n                <Level_Number>1</Level_Number>\r\n                <Level_Value" +
            ">2880</Level_Value>\r\n                <cPoint>(-1.60326584326685,11029.817984624," +
            "2880)</cPoint>\r\n                <cPoint>(6798.39673415673,11029.817984624,2880)<" +
            "/cPoint>\r\n                <cPoint>(6798.39673415673,-0.18201537601999,2880)</cPo" +
            "int>\r\n                <cPoint>(-1.60326584326685,-0.18201537601999,2880)</cPoint" +
            ">\r\n                <cPoint>(-1.60326584326685,11029.817984624,2880)</cPoint>\r\n  " +
            "          </Hatch1>\r\n            <Hatch14>\r\n                <Level_Name>2ndfloor" +
            "</Level_Name>\r\n                <Level_Number>2</Level_Number>\r\n                <" +
            "Level_Value>5760</Level_Value>\r\n                <cPoint>(0,11030,5760)</cPoint>\r" +
            "\n                <cPoint>(6800,11030,5760)</cPoint>\r\n                <cPoint>(68" +
            "00,0,5760)</cPoint>\r\n                <cPoint>(0,0,5760)</cPoint>\r\n              " +
            "  <cPoint>(0,11030,5760)</cPoint>\r\n            </Hatch14>\r\n            <Hatch21>" +
            "\r\n                <Level_Name>2ndfloor</Level_Name>\r\n                <Level_Numb" +
            "er>2</Level_Number>\r\n                <Level_Value>5760</Level_Value>\r\n          " +
            "      <cPoint>(1020,11365,5760)</cPoint>\r\n                <cPoint>(5780,-335.000" +
            "000000001,5760)</cPoint>\r\n                <cPoint>(5780,-335.000000000001,5760)<" +
            "/cPoint>\r\n            </Hatch21>\r\n            <Hatch296>\r\n                <Level" +
            "_Name>groundfloor</Level_Name>\r\n                <Level_Number>0</Level_Number>\r\n" +
            "                <Level_Value>0</Level_Value>\r\n                <cPoint>(6800,2940" +
            ",0)</cPoint>\r\n                <cPoint>(6800,0,0)</cPoint>\r\n                <cPoi" +
            "nt>(0,0,0)</cPoint>\r\n                <cPoint>(0,11030,0)</cPoint>\r\n             " +
            "   <cPoint>(6800,11030,0)</cPoint>\r\n                <cPoint>(6800,9240,0)</cPoin" +
            "t>\r\n                <cPoint>(10000,9240,0)</cPoint>\r\n                <cPoint>(10" +
            "000,2940,0)</cPoint>\r\n                <cPoint>(6800,2940,0)</cPoint>\r\n          " +
            "  </Hatch296>\r\n            <Hatch4>\r\n                <Level_Name>1stfloor</Level" +
            "_Name>\r\n                <Level_Number>1</Level_Number>\r\n                <Level_V" +
            "alue>2880</Level_Value>\r\n                <cPoint>(6798.39673415673,9539.81798462" +
            "398,2880)</cPoint>\r\n                <cPoint>(10230.3950501274,9539.81798462398,2" +
            "880)</cPoint>\r\n                <cPoint>(10230.3950501274,2639.81798462398,2880)<" +
            "/cPoint>\r\n                <cPoint>(6798.39673415673,2639.81798462398,2880)</cPoi" +
            "nt>\r\n                <cPoint>(6798.39673415673,9539.81798462398,2880)</cPoint>\r\n" +
            "            </Hatch4>\r\n        </Floors>\r\n        <Walls>\r\n            <Polyline" +
            "13>\r\n                <Level_Name>1stfloor</Level_Name>\r\n                <Level_N" +
            "umber>1</Level_Number>\r\n                <Level_Value>2880</Level_Value>\r\n       " +
            "         <cPoint>(-1.60326584326685,11029.817984624,2880)</cPoint>\r\n            " +
            "    <cPoint>(6798.39673415673,11029.817984624,2880)</cPoint>\r\n                 <" +
            "Levels><cPoint>(6798.39673415673,-0.18201537601999,2880)</cPoint>\r\n             " +
            "   <cPoint>(-1.60326584326685,-0.18201537601999,2880)</cPoint>\r\n                " +
            "<cPoint>(-1.60326584326685,11029.817984624,2880)</cPoint>\r\n            </Polylin" +
            "e13>\r\n            <Polyline26>\r\n                <Level_Name>2ndfloor</Level_Name" +
            ">\r\n                <Level_Number>2</Level_Number>\r\n                <Level_Value>" +
            "5760</Level_Value>\r\n                <cPoint>(0,11030,5760)</cPoint>\r\n           " +
            "     <cPoint>(6800,11030,5760)</cPoint>\r\n                <cPoint>(6800,0,5760)</" +
            "cPoint>\r\n                <cPoint>(0,0,5760)</cPoint>\r\n                <cPoint>(0" +
            ",11030,5760)</cPoint>\r\n            </Polyline26>\r\n            <Polyline311>\r\n   " +
            "             <Level_Name>groundfloor</Level_Name>\r\n                <Level_Number" +
            ">0</Level_Number>\r\n                <Level_Value>0</Level_Value>\r\n               " +
            " <cPoint>(6800,2940,0)</cPoint>\r\n                <cPoint>(6800,0,0)</cPoint>\r\n  " +
            "              <cPoint>(0,0,0)</cPoint>\r\n                <cPoint>(0,11030,0)</cPo" +
            "int>\r\n                <cPoint>(6800,11030,0)</cPoint>\r\n                <cPoint>(" +
            "6800,9240,0)</cPoint>\r\n                <cPoint>(10000,9240,0)</cPoint>\r\n        " +
            "        <cPoint>(10000,2940,0)</cPoint>\r\n                <cPoint>(6800,2940,0)</" +
            "cPoint>\r\n            </Polyline311>\r\n        </Walls>\r\n    </CAP>\r\n</Export>")]
        public string FloorPoints {
            get {
                return ((string)(this["FloorPoints"]));
            }
            set {
                this["FloorPoints"] = value;
            }
        }
    }
}
